-- H2 Database Schema
-- Based on migration scripts V1, V2, and V3

-- Create table for users
CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    FIRSTNAME VARCHAR(64) NOT NULL,
    LASTNAME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PASSWORD_EXPIRATION TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT CHK_USERS_STATUS CHECK (
        STATUS IN ('CREATED', 'ACTIVE', 'INACTIVE', 'DELETED')
    ),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

-- Add indexes for users table
CREATE INDEX IF NOT EXISTS IDX_USERS_ID ON PUBLIC.USERS (ID);
CREATE INDEX IF NOT EXISTS IDX_USERS_FIRSTNAME ON PUBLIC.USERS (FIRSTNAME);
CREATE INDEX IF NOT EXISTS IDX_USERS_LASTNAME ON PUBLIC.USERS (LASTNAME);
CREATE INDEX IF NOT EXISTS IDX_USERS_USERNAME ON PUBLIC.USERS (USERNAME);
CREATE INDEX IF NOT EXISTS IDX_USERS_STATUS ON PUBLIC.USERS (STATUS);

-- Create oauth2_registered_client table
CREATE TABLE IF NOT EXISTS PUBLIC.OAUTH2_REGISTERED_CLIENT (
    ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    CLIENT_ID VARCHAR(100) NOT NULL,
    CLIENT_ID_ISSUED_AT TIMESTAMP NOT NULL,
    CLIENT_SECRET VARCHAR(255),
    CLIENT_SECRET_EXPIRES_AT TIMESTAMP,
    CLIENT_NAME VARCHAR(200) NOT NULL,
    CLIENT_AUTHENTICATION_METHODS TEXT NOT NULL,
    AUTHORIZATION_GRANT_TYPES TEXT NOT NULL,
    REDIRECT_URIS TEXT,
    POST_LOGOUT_REDIRECT_URIS TEXT,
    SCOPES TEXT,
    CLIENT_SETTINGS TEXT NOT NULL,
    TOKEN_SETTINGS TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_OAUTH2_CLIENT_ID UNIQUE (CLIENT_ID),
    CONSTRAINT UQ_OAUTH2_CLIENT_NAME UNIQUE (CLIENT_NAME),
    CONSTRAINT CHK_CLIENT_AUTH_METHODS_VALUES CHECK (
        CLIENT_AUTHENTICATION_METHODS REGEXP '^(client_secret_basic|client_secret_post|private_key_jwt|client_secret_jwt|none)(,(client_secret_basic|client_secret_post|private_key_jwt|client_secret_jwt|none))*$'
    ),
    CONSTRAINT CHK_AUTHORIZATION_GRANT_TYPES_VALUES CHECK (
        AUTHORIZATION_GRANT_TYPES REGEXP '^(authorization_code|client_credentials|refresh_token|urn:ietf:params:oauth:grant-type:device_code|urn:ietf:params:oauth:grant-type:token-exchange)(,(authorization_code|client_credentials|refresh_token|urn:ietf:params:oauth:grant-type:device_code|urn:ietf:params:oauth:grant-type:token-exchange))*$'
    )
);

-- Create oauth2_authorization table
CREATE TABLE IF NOT EXISTS PUBLIC.OAUTH2_AUTHORIZATION (
    ID UUID NOT NULL DEFAULT RANDOM_UUID(),
    REGISTERED_CLIENT_ID UUID NOT NULL,
    PRINCIPAL_NAME VARCHAR(200) NOT NULL,
    AUTHORIZATION_GRANT_TYPE VARCHAR(100) NOT NULL,
    AUTHORIZED_SCOPES TEXT,
    TOKENS TEXT NOT NULL,
    ATTRIBUTES TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_OAUTH2_AUTH_CLIENT FOREIGN KEY (REGISTERED_CLIENT_ID)
        REFERENCES PUBLIC.OAUTH2_REGISTERED_CLIENT(ID)
);

