-- Create oauth2_authorization table
CREATE TABLE PUBLIC.OAUTH2_AUTHORIZATION (
    ID UUID NOT NULL DEFAULT UUID_GENERATE_V4 (),
    REGISTERED_CLIENT_ID UUID NOT NULL,
    PRINCIPAL_NAME CHARACTER VARYING(200) NOT NULL,
    AUTHORIZATION_GRANT_TYPE CHARACTER VARYING(100) NOT NULL,
    AUTHORIZED_SCOPES TEXT,
    TOKENS JSONB NOT NULL,
    ATTRIBUTES JSONB NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (REGISTERED_CLIENT_ID) REFERENCES PUBLIC.OAUTH2_REGISTERED_CLIENT(ID)
);