-- Create oauth2_authorization_consent table
CREATE TABLE PUBLIC.OAUTH2_AUTHORIZATION_CONSENT (
    REGISTERED_CLIENT_ID CHARACTER VARYING(100) NOT NULL,
    PRINCIPAL_NAME CHARACTER VARYING(200) NOT NULL,
    AUTHORITIES CHARACTER VARYING(1000) NOT NULL,
    PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);
